# Generated by Django 4.2.23 on 2025-08-11 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recetas_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="receta",
            name="imagen",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="receta",
            name="slug",
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name="ingrediente",
            name="unidad",
            field=models.CharField(
                choices=[
                    ("unidades", "Unidades"),
                    ("litros", "Litros"),
                    ("mililitros", "Mililitros"),
                    ("cuchadaras", "Cucharadas"),
                    ("gramos", "Gramos"),
                    ("kilos", "Kilos"),
                    ("shots", "Shots"),
                    ("taza", "Taza"),
                ],
                default="unidades",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="receta",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
